language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install flask
  - pip install requests
  - pip install coverage
  - pip install flake8
script:
  - coverage run -m unittest discover

#  - python -m unittest discover        # no module named 'requests'
#  - coverage run -m unittest discover # could not find coverage
