language: python
python:
  - "3.6"      # current default Python on Travis CI

script:
  - python -m unittest discover        # no module named 'requests'
#  - coverage run -m unittest discover # could not find coverage

# safelist
#branches:
#  only:
#  - master
