language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install flask
  - pip install requests
  - pip install coverage
  - pip install flake8

script:
  - flake8                                       # style checker
  - coverage run -m unittest discover            # Run the tests and check for test coverage
  - coverage run -m --branch unittest discover
  - coverage report -m                           # Generate test coverage report


  # - coverage html
  # - python3 app.py
  # - codecov                           # Upload the report to codecov.
